### PR TITLE
problem with hanging on Yosemite

### PR DESCRIPTION
**Pull request by mscuthbert**
The conversion from opt to DisplayID was not doing an unsigned conversion which was an occasional problem.  The call to CGDisplayIOServicePort() does not seem to work in some cases if CGGetOnlineDisplayList() has never been called.  This fix seems to work well on Yosemite; though I need to confess that I'm a poor C programmer (great python, but not much for this code) so please check the code before merging.

Removed warnings relating to coercing CGDirectDisplayID to pointer (apparently, even though we know that it is, Apple doesn't think so).

I should have a patch that does not call CGDisplayIOServicePort() in the future if desired.

### CODE REVIEW

**Comment by CdLbB** [comment]
Thank you very much for this pull request. I am looking at it.

However, it has been a number of years since I last looked at fb-rotate; I have to remember how it works. So it may take me a bit.

Again, Thanks.
Eric

**Comment by mscuthbert** [comment]
Thanks! It's not urgent, but I think it'd help people!

**Comment by CdLbB** [comment]
I finally got a chance to go through all your proposed changes (Pull Requests #1,#2, #3), and they all make sense.

I'm going to set up a couple multi-monitor arrangements this weekend and test everything. As I have mentioned I haven't played with fb-rotate (or C programming) for quite a while, so this should be a good exercise. If everything works -- I expect it will -- I'll merge everything. Then I'll update the ReadMe.

Again, thanks for all your efforts.
--Eric

**Comment by mscuthbert** [comment]
Thanks! Maybe two lapsed C programmers will be as good as any.  :-)  Btw -- I made a DMG of an .app package that calls "fb-rotate -d 1 -r 1" at https://dl.dropboxusercontent.com/u/21626762/FBRotate.dmg which has been super helpful for me. :-)

**Comment by CdLbB** [comment]
I tested all three proposed changes (pull requests #1,#2, #3), and they work as expected on Mavericks and Yosemite. However, the -d 1 option (pull request #2) interacts weirdly with the -m option, so I am merging pull request #1 and holding off on the other two for the moment. I have two ideas for addressing the problem, which I will detail in the comments to pull request #2.

**Pull request merged**
